[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "psst"
version = "0.0.2"
requires-python = ">=3.9"
dependencies = [
    "attrs",
    "pyyaml",
    "torch",
]

[tool.setuptools.packages.find]
where = ["psst"]