device: 'cuda:2'
output_directory: '../mike_outputs/nw_theta'
mode: 'theta' # Can be 'mixed', 'theta', or 'good'
resolution: [512, 512]
layer_sizes: [3200, 2000, 1000, 2]
kernel_sizes: [5, 3, 3, 3, 3, 5, 5]
pool_sizes: [2, 2, 2, 2, 2, 2, 1]
channels: [50, 100, 200, 400, 800, 1600, 3200]
phi_range: 
    min: 0.000001
    max: 0.01
nw_range: 
    min: 10
    max: 300000
eta_sp_range: 
    min: 1
    max: 3500000
bg_range: 
    min: 0.3
    max: 1.53
    mu: -0.54748
    sigma: 0.30963
bth_range: 
    min: 0.2
    max: 0.8
    mu: -1.05196
    sigma: 0.2248
pe_range: 
    min: 3
    max: 18
    mu: 1.95
    sigma: 0.36
num_nw_strips: 8
batch_size: 60
train_size: 60000
test_size: 3000
epochs: 50
learning_rate: 0.001